// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"

	mock "github.com/stretchr/testify/mock"
)

// AddOnUsecase is an autogenerated mock type for the AddOnUsecase type
type AddOnUsecase struct {
	mock.Mock
}

// GetAllAddOn provides a mock function with given fields:
func (_m *AddOnUsecase) GetAllAddOn() ([]dto.AddOnResponse, error) {
	ret := _m.Called()

	var r0 []dto.AddOnResponse
	if rf, ok := ret.Get(0).(func() []dto.AddOnResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AddOnResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAddOnUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddOnUsecase creates a new instance of AddOnUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddOnUsecase(t mockConstructorTestingTNewAddOnUsecase) *AddOnUsecase {
	mock := &AddOnUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
