// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "final-project-backend/entity"

	mock "github.com/stretchr/testify/mock"
)

// AddressRepository is an autogenerated mock type for the AddressRepository type
type AddressRepository struct {
	mock.Mock
}

// CreateAddress provides a mock function with given fields: address
func (_m *AddressRepository) CreateAddress(address entity.Address) (*entity.Address, error) {
	ret := _m.Called(address)

	var r0 *entity.Address
	if rf, ok := ret.Get(0).(func(entity.Address) *entity.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Address) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddressBySpecificUser provides a mock function with given fields: userId, addressId
func (_m *AddressRepository) GetAddressBySpecificUser(userId int, addressId int) (*entity.Address, error) {
	ret := _m.Called(userId, addressId)

	var r0 *entity.Address
	if rf, ok := ret.Get(0).(func(int, int) *entity.Address); ok {
		r0 = rf(userId, addressId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userId, addressId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddressByUserId provides a mock function with given fields: userId
func (_m *AddressRepository) GetAddressByUserId(userId int) ([]entity.Address, error) {
	ret := _m.Called(userId)

	var r0 []entity.Address
	if rf, ok := ret.Get(0).(func(int) []entity.Address); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAddress provides a mock function with given fields:
func (_m *AddressRepository) GetAllAddress() ([]entity.Address, error) {
	ret := _m.Called()

	var r0 []entity.Address
	if rf, ok := ret.Get(0).(func() []entity.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAddressRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddressRepository creates a new instance of AddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddressRepository(t mockConstructorTestingTNewAddressRepository) *AddressRepository {
	mock := &AddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
