// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"

	mock "github.com/stretchr/testify/mock"
)

// PaymenUsecase is an autogenerated mock type for the PaymenUsecase type
type PaymenUsecase struct {
	mock.Mock
}

// PayUserShipping provides a mock function with given fields: request
func (_m *PaymenUsecase) PayUserShipping(request dto.PaymentPayRequest) (*dto.PaymentResponse, error) {
	ret := _m.Called(request)

	var r0 *dto.PaymentResponse
	if rf, ok := ret.Get(0).(func(dto.PaymentPayRequest) *dto.PaymentResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.PaymentPayRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPaymenUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewPaymenUsecase creates a new instance of PaymenUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPaymenUsecase(t mockConstructorTestingTNewPaymenUsecase) *PaymenUsecase {
	mock := &PaymenUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
