// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"

	mock "github.com/stretchr/testify/mock"
)

// PromoUserUsecase is an autogenerated mock type for the PromoUserUsecase type
type PromoUserUsecase struct {
	mock.Mock
}

// GetAllPromoUserByUserId provides a mock function with given fields: userId
func (_m *PromoUserUsecase) GetAllPromoUserByUserId(userId int) ([]dto.PromoUserResponse, error) {
	ret := _m.Called(userId)

	var r0 []dto.PromoUserResponse
	if rf, ok := ret.Get(0).(func(int) []dto.PromoUserResponse); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PromoUserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPromoUserUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewPromoUserUsecase creates a new instance of PromoUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPromoUserUsecase(t mockConstructorTestingTNewPromoUserUsecase) *PromoUserUsecase {
	mock := &PromoUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
