// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"

	mock "github.com/stretchr/testify/mock"
)

// SizeUsecase is an autogenerated mock type for the SizeUsecase type
type SizeUsecase struct {
	mock.Mock
}

// GetAllSize provides a mock function with given fields:
func (_m *SizeUsecase) GetAllSize() ([]dto.SizeResponse, error) {
	ret := _m.Called()

	var r0 []dto.SizeResponse
	if rf, ok := ret.Get(0).(func() []dto.SizeResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.SizeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSizeUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewSizeUsecase creates a new instance of SizeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSizeUsecase(t mockConstructorTestingTNewSizeUsecase) *SizeUsecase {
	mock := &SizeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
