// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "final-project-backend/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// GetUserById provides a mock function with given fields: userId
func (_m *UserUsecase) GetUserById(userId int) (*dto.UserResponse, error) {
	ret := _m.Called(userId)

	var r0 *dto.UserResponse
	if rf, ok := ret.Get(0).(func(int) *dto.UserResponse); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: request
func (_m *UserUsecase) TopUp(request dto.TopUpRequest) (*dto.UserResponse, error) {
	ret := _m.Called(request)

	var r0 *dto.UserResponse
	if rf, ok := ret.Get(0).(func(dto.TopUpRequest) *dto.UserResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.TopUpRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserById provides a mock function with given fields: request
func (_m *UserUsecase) UpdateUserById(request dto.UserUpdateRequest) (*dto.UserResponse, error) {
	ret := _m.Called(request)

	var r0 *dto.UserResponse
	if rf, ok := ret.Get(0).(func(dto.UserUpdateRequest) *dto.UserResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.UserUpdateRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserUsecase(t mockConstructorTestingTNewUserUsecase) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
